version: '3'
services:
  nginx:
    image: nginx:1.15
    container_name: nginx
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
    ports:
      - "127.0.0.1:80:80"
    restart: on-failure
